language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install: "pip install -r requirements/dev.txt"
script: "python manage.py test"
