"""add assets table

Revision ID: 2113da98e6fe
Revises: bec6aa2c4583
Create Date: 2017-08-26 12:28:20.942650

"""

# revision identifiers, used by Alembic.
revision = '2113da98e6fe'
down_revision = 'bec6aa2c4583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_file_name'), 'assets', ['file_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_file_name'), table_name='assets')
    op.drop_table('assets')
    ### end Alembic commands ###
