"""add some indexes

Revision ID: 3e7ca212b569
Revises: a502c23d7703
Create Date: 2018-05-30 21:40:47.612650

"""

# revision identifiers, used by Alembic.
revision = '3e7ca212b569'
down_revision = 'a502c23d7703'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_lessons_lesson'), 'lessons', ['lesson'], unique=False)
    op.create_index(op.f('ix_lessons_user_id'), 'lessons', ['user_id'], unique=False)
    op.create_index(op.f('ix_scores_is_exam'), 'scores', ['is_exam'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_index(op.f('ix_screens_name'), 'screens', ['name'], unique=False)
    op.create_index(op.f('ix_screens_user_id'), 'screens', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screens_user_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_name'), table_name='screens')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_is_exam'), table_name='scores')
    op.drop_index(op.f('ix_lessons_user_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson'), table_name='lessons')
    op.alter_column('lessons', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###
