"""empty message

Revision ID: 533437529fea
Revises: f6db270651bd
Create Date: 2019-03-02 13:00:51.558900

"""

# revision identifiers, used by Alembic.
revision = '533437529fea'
down_revision = 'f6db270651bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ios_device_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_store_validated', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_ios_device_info_user_id'), 'ios_device_info', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ios_device_info_user_id'), table_name='ios_device_info')
    op.drop_table('ios_device_info')
    ### end Alembic commands ###
