"""empty message

Revision ID: 7a27ef43e028
Revises: af6bd71c309b
Create Date: 2017-02-18 11:45:34.064113

"""

# revision identifiers, used by Alembic.
revision = '7a27ef43e028'
down_revision = 'af6bd71c309b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exam_points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exam_points')
    ### end Alembic commands ###
