"""add table scores

Revision ID: 92ae03cb2b03
Revises: 13c8895fd5c
Create Date: 2016-11-26 12:28:55.627379

"""

# revision identifiers, used by Alembic.
revision = '92ae03cb2b03'
down_revision = '13c8895fd5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_game', 'scores', ['user_id', 'game'], unique=False)
    op.create_index(op.f('ix_scores_game'), 'scores', ['game'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_game'), table_name='scores')
    op.drop_index('idx_user_game', table_name='scores')
    op.drop_table('scores')
    ### end Alembic commands ###
