"""add login_info table

Revision ID: 9b78fcae9634
Revises: 5ed8faf8629c
Create Date: 2017-10-14 12:52:05.353866

"""

# revision identifiers, used by Alembic.
revision = '9b78fcae9634'
down_revision = '5ed8faf8629c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remote_addr', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_info')
    ### end Alembic commands ###
