"""empty message

Revision ID: af6bd71c309b
Revises: cacff2c5b093
Create Date: 2017-02-18 09:35:47.495299

"""

# revision identifiers, used by Alembic.
revision = 'af6bd71c309b'
down_revision = 'cacff2c5b093'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tutorial_completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tutorial_completed')
    ### end Alembic commands ###
