"""add state field to score

Revision ID: bec9b30e5798
Revises: 92ae03cb2b03
Create Date: 2016-11-28 23:03:12.346330

"""

# revision identifiers, used by Alembic.
revision = 'bec9b30e5798'
down_revision = '92ae03cb2b03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('state', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'state')
    ### end Alembic commands ###
