"""add table lessons

Revision ID: cacff2c5b093
Revises: bec9b30e5798
Create Date: 2017-02-04 09:36:41.061217

"""

# revision identifiers, used by Alembic.
revision = 'cacff2c5b093'
down_revision = 'bec9b30e5798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lesson', sa.String(length=64), nullable=True),
    sa.Column('total_pages_viewed', sa.Integer(), nullable=True),
    sa.Column('clicks_forward', sa.Integer(), nullable=True),
    sa.Column('clicks_backward', sa.Integer(), nullable=True),
    sa.Column('clicks_menu', sa.Integer(), nullable=True),
    sa.Column('clicks_lesson_repeat', sa.Integer(), nullable=True),
    sa.Column('way_exit', sa.String(length=64), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    ### end Alembic commands ###
