"""empty message

Revision ID: f6db270651bd
Revises: 3e7ca212b569
Create Date: 2018-09-09 18:39:53.565986

"""

# revision identifiers, used by Alembic.
revision = 'f6db270651bd'
down_revision = '3e7ca212b569'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    ### end Alembic commands ###
